language: node_js

dist: xenial

services:
  - postgresql

sudo: true

node_js:
  - "12"
  - "10"
  - "8"
  - "6"
  - "4"

env:
  - CC=clang CXX=clang++ npm_config_clang=1 PGUSER=postgres PGDATABASE=postgres PGHOST=localhost
